site_url: https://timdavidlee.github.io/everything-but-the-ml/
site_name: School of Machine Learning Engineering, without the Algos
docs_dir: school-of-mle
theme:
    name: material
nav:
- Home: index.md
- Core System: sys.md
- Git: git.md
- Airflow: airflow/intro.md
- VIM: Basic file editng: vim/basics.md
- API/RESTFUL: api.md
- HTTP: http.md
- FileSystems: sys.md
- AWS: 
    - Buckets: aws/buckets.md
    - Boto Library: aws/buckets.md
- Bash/Shell:
    - Quality of Life Installs: bash/quality-of-life.md
    - Types of Linux: bash/linux-types.md
    - Command Line "Fu": piping.md
- Data Formats:
    - CSV: data-formats/csv.md
    - json: data-formats/json.md
    - parquet: data-formats/parquet.md
    - pickle: data-formats/pickle.md
- Docker:
    - Why docker?: docker/intro.md
    - Docker Basics: docker/
    - Building Images: docker/building_images.md
- Git:
    - Getting other's code: git/cloning-basics.md
    - Repo-Level Commands: git/repo-level-actions.md
    - Contributing: git/branches.md
- SSH:
    - Getting into a VM: ssh/let-me-in.md
    - Tunneling to a VM: ssh/tunneling.md


