site_url: https://timdavidlee.github.io/everything-but-the-ml/
site_name: School of Machine Learning Engineering, without the Algos
docs_dir: school-of-mle
theme:
    name: material
    palette:
        primary: teal
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
- Home: index.md
- Linux/Shell:
    - Quality of Life Installs: linux/quality-of-life.md
    - Types of Linux: linux/linux-types.md
    - Command Line "Fu": linux/piping.md
- Text Editing: 
    - Basic file editing in VI: vim/basics.md
- Git:
    - Getting other's code: git/cloning-basics.md
    - Repo-Level Commands: git/repo-level-actions.md
    - Contributing: git/branches.md
- SSH:
    - Getting into a VM: ssh/let-me-in.md
    - Tunneling to a VM: ssh/tunneling.md
- Core System: sys.md
- API/RESTFUL: api.md
- HTTP: http.md
- FileSystems: sys.md
- AWS: 
    - Buckets: aws/buckets.md
    - Boto Library: aws/boto.md
- Data Formats:
    - CSV: data-formats/csv.md
    - json: data-formats/json.md
    - parquet: data-formats/parquet.md
    - pickle: data-formats/pickle.md
- Docker:
    - Why docker?: docker/intro.md
    - Docker Basics: docker/basics.md
    - Building Images: docker/building_images.md
- Python:
    - Why is python so slow: python/python-is-slow.md
    - Managing Python:
        - Versions and Envs: python/versions-and-envs.md
        - Managing Pip: python/pip.md
    - Processing Efficiently:
        - Collections: python/collections.md
        - Parallel Processing: python/parallel_processing.md
        - List Comprehensions: python/list_comprehensions.md
        - Generators: python/generators.md
        - Data Classes: python/dataclasses.md
    - Organization:
        - Testing: python/pytest.md
        - Type Hinting: python/linting.md
- Airflow: airflow/intro.md
